return function(p, _opts)
  return {
    -- oil.nvim
    OilDir = { fg = p.ibad },
    OilDirIcon = { fg = p.ibad },
    OilFile = { fg = p.fg },
    OilLink = { fg = p.water, underline = true },
    OilLinkTarget = { fg = p.water },
    OilCreate = { fg = p.scrub },
    OilDelete = { fg = p.blood },
    OilMove = { fg = p.spice },
    OilCopy = { fg = p.ibad },
    OilChange = { fg = p.spice },
    OilRestore = { fg = p.scrub },
    OilPurge = { fg = p.blood },
    OilTrash = { fg = p.blood },
    OilSize = { fg = p.muted },
    OilMtime = { fg = p.muted },
    OilPermissionNone = { fg = p.linenr },
    OilPermissionRead = { fg = p.spice },
    OilPermissionWrite = { fg = p.ember },
    OilPermissionExecute = { fg = p.scrub },
    OilTypeDir = { fg = p.ibad },
    OilTypeFile = { fg = p.fg_dim },
    OilTypeLink = { fg = p.water },

    -- telescope.nvim
    TelescopeNormal = { fg = p.fg, bg = p.bg_float },
    TelescopeBorder = { fg = p.border, bg = p.bg_float },
    TelescopeTitle = { fg = p.bg, bg = p.spice, bold = true },
    TelescopePromptNormal = { fg = p.fg, bg = p.bg_alt },
    TelescopePromptBorder = { fg = p.border, bg = p.bg_alt },
    TelescopePromptTitle = { fg = p.bg, bg = p.ember, bold = true },
    TelescopePromptPrefix = { fg = p.spice },
    TelescopePromptCounter = { fg = p.muted },
    TelescopeResultsNormal = { fg = p.fg_dim, bg = p.bg_float },
    TelescopeResultsBorder = { fg = p.border, bg = p.bg_float },
    TelescopeResultsTitle = { fg = p.bg_float, bg = p.bg_float },
    TelescopePreviewNormal = { fg = p.fg, bg = p.bg_float },
    TelescopePreviewBorder = { fg = p.border, bg = p.bg_float },
    TelescopePreviewTitle = { fg = p.bg, bg = p.scrub, bold = true },
    TelescopeSelection = { fg = p.fg_bright, bg = p.bg_sel },
    TelescopeSelectionCaret = { fg = p.spice, bg = p.bg_sel },
    TelescopeMultiSelection = { fg = p.spice },
    TelescopeMatching = { fg = p.spice, bold = true },

    -- blink.cmp
    BlinkCmpMenu = { fg = p.fg_dim, bg = p.bg_float },
    BlinkCmpMenuBorder = { fg = p.border, bg = p.bg_float },
    BlinkCmpMenuSelection = { fg = p.fg_bright, bg = p.bg_sel },
    BlinkCmpScrollBarThumb = { bg = p.border },
    BlinkCmpScrollBarGutter = { bg = p.bg_float },
    BlinkCmpLabel = { fg = p.fg_dim },
    BlinkCmpLabelDeprecated = { fg = p.muted, strikethrough = true },
    BlinkCmpLabelMatch = { fg = p.spice, bold = true },
    BlinkCmpLabelDetail = { fg = p.muted },
    BlinkCmpLabelDescription = { fg = p.muted },
    BlinkCmpKind = { fg = p.ibad },
    BlinkCmpSource = { fg = p.muted },
    BlinkCmpGhostText = { fg = p.linenr, italic = true },
    BlinkCmpDoc = { fg = p.fg, bg = p.bg_float },
    BlinkCmpDocBorder = { fg = p.border, bg = p.bg_float },
    BlinkCmpDocSeparator = { fg = p.border, bg = p.bg_float },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg_float },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg_float },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.spice, bold = true },

    -- trouble.nvim
    TroubleNormal = { fg = p.fg_dim, bg = p.bg_float },
    TroubleNormalNC = { fg = p.fg_dim, bg = p.bg_float },
    TroubleText = { fg = p.fg_dim },
    TroubleCount = { fg = p.spice, bg = p.bg_sel },
    TroubleIndent = { fg = p.border },
    TroublePos = { fg = p.muted },
    TroubleFileName = { fg = p.fg },
    TroubleSource = { fg = p.muted },
    TroubleCode = { fg = p.muted },

    -- toggleterm.nvim
    ToggleTerm1FloatBorder = { fg = p.border, bg = p.bg_float },
    ToggleTerm2FloatBorder = { fg = p.border, bg = p.bg_float },
    ToggleTermNormal = { fg = p.fg, bg = p.bg_float },
    ToggleTermNormalFloat = { fg = p.fg, bg = p.bg_float },

    -- mini.nvim
    MiniStatuslineModeNormal = { fg = p.bg, bg = p.spice, bold = true },
    MiniStatuslineModeInsert = { fg = p.bg, bg = p.scrub, bold = true },
    MiniStatuslineModeVisual = { fg = p.bg, bg = p.ibad, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg, bg = p.blood, bold = true },
    MiniStatuslineModeCommand = { fg = p.bg, bg = p.ember, bold = true },
    MiniStatuslineModeOther = { fg = p.bg, bg = p.water, bold = true },
    MiniStatuslineDevinfo = { fg = p.fg_dim, bg = p.bg_alt },
    MiniStatuslineFilename = { fg = p.fg_dim, bg = p.bg_alt },
    MiniStatuslineFileinfo = { fg = p.fg_dim, bg = p.bg_alt },
    MiniStatuslineInactive = { fg = p.muted, bg = p.bg_alt },
    MiniSurround = { fg = p.bg, bg = p.spice },
    MiniCursorword = { bg = p.bg_sel },
    MiniCursorwordCurrent = { bg = p.bg_sel },
    MiniIndentscopeSymbol = { fg = p.border },
    MiniTrailspace = { bg = p.blood },
    MiniIconsAzure = { fg = p.ibad },
    MiniIconsBlue = { fg = p.ibad },
    MiniIconsCyan = { fg = p.water },
    MiniIconsGreen = { fg = p.scrub },
    MiniIconsGrey = { fg = p.fg_dim },
    MiniIconsOrange = { fg = p.ember },
    MiniIconsPurple = { fg = p.melange },
    MiniIconsRed = { fg = p.blood },
    MiniIconsYellow = { fg = p.spice },
  }
end
